export enum UserSynchronizationChannel {
  NOTIFICATIONS = 'NOTIFICATIONS',
  NOTIFICATIONS_USER_REQUEST = 'NOTIFICATIONS_USER_REQUEST',
  GEOGRAPHIC_LAYERS = 'GEOGRAPHIC_LAYERS',
  LAW_PROCEDURE_LAYERS = 'LAW_PROCEDURE_LAYERS',
}

export enum UserSynchronizationEvent {
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
  SEND_NOTIFICATION_USER_REQUEST = 'SEND_NOTIFICATION_USER_REQUEST',
  SHAPEFILE_PROCESS = 'SHAPEFILE_PROCESS',
  LAW_PROCEDURE_SHAPEFILE_PROCESS  = 'LAW_PROCEDURE_SHAPEFILE_PROCESS',
}

export enum SocketChannel {
     GEODATA_IMPORTER = 'GEODATA_IMPORTER',
}

export enum SocketEvent {
    WAITING = 'WAITING',
    STARTED = 'STARTED',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
    CANCELED = 'CANCELED',
}
