import {
    Alignment,
    Autoformat,
    Bold,
    Bookmark,
    Italic,
    Strikethrough,
    Subscript,
    Superscript,
    Underline,
    BlockQuote,
    Base64UploadAdapter,
    CloudServices,
    Essentials,
    FindAndReplace,
    FontBackgroundColor,
    FontColor,
    FontFamily,
    FontSize,
    Heading,
    HorizontalLine,
    Image,
    ImageCaption,
    ImageResize,
    ImageStyle,
    ImageToolbar,
    ImageUpload,
    ImageInsert,
    PictureEditing,
    Indent,
    IndentBlock,
    Link,
    List,
    ListProperties,
    MediaEmbed,
    Mention,
    PageBreak,
    Paragraph,
    PasteFromOffice,
    RemoveFormat,
    SpecialCharacters,
    SpecialCharactersEssentials,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    ClassicEditor,
} from 'ckeditor5';
import esTranslations from 'ckeditor5/translations/es.js';
import { CustomVariablesPlugin } from '../plugins/custom-variables.plugin';

export const EditorSetup = {
    config: {
        licenseKey: 'GPL',
        plugins: [
            Essentials,
            Alignment,
            Autoformat,
            BlockQuote,
            Bold,
            Bookmark,
            CloudServices,
            FindAndReplace,
            FontBackgroundColor,
            FontColor,
            FontFamily,
            FontSize,
            Heading,
            HorizontalLine,
            Image,
            ImageCaption,
            ImageResize,
            ImageStyle,
            ImageToolbar,
            ImageUpload,
            ImageInsert,
            Base64UploadAdapter,
            Indent,
            IndentBlock,
            Italic,
            Link,
            List,
            ListProperties,
            MediaEmbed,
            Mention,
            PageBreak,
            Paragraph,
            PasteFromOffice,
            PictureEditing,
            RemoveFormat,
            SpecialCharacters,
            SpecialCharactersEssentials,
            Strikethrough,
            Subscript,
            Superscript,
            Table,
            TableCaption,
            TableCellProperties,
            TableColumnResize,
            TableProperties,
            TableToolbar,
            TextTransformation,
            Underline,
            // Plugins personalizados
            CustomVariablesPlugin,
        ],
        toolbar: {
            items: [
                // --- Document-wide tools ----------------------------------------------------------------------
                'undo',
                'redo',
                '|',
                // --- Block-level formatting -------------------------------------------------------------------
                'heading',
                '|',

                // --- Basic styles and inline formatting -------------------------------------------------------
                'bold',
                'italic',
                'underline',
                // {
                //     label: 'Estilos básicos',
                //     icon: 'text',
                //     items: ['strikethrough', 'superscript', 'subscript'],
                // },
                // 'removeFormat',
                '|',
                // --- Font formatting -------------------------------------------------------------------
                'fontSize',
                'fontFamily',
                'fontColor',
                'fontBackgroundColor',
                '|',

                // --- Text alignment ---------------------------------------------------------------------------
                'alignment',
                'lineHeight',
                '|',

                // --- Lists and indentation --------------------------------------------------------------------
                'bulletedList',
                'numberedList',
                'multilevelList',
                '|',
                'outdent',
                'indent',
                '|',
                'formatPainter',
                'caseChange',
                'findAndReplace',
                'selectAll',
                'wproofreader',
                '|',
                'insertTemplate',
                'tableOfContents',
                '|',

                // --- "Insertables" ----------------------------------------------------------------------------
                'link',
                'bookmark',
                'insertImage',
                'ckbox',
                'insertTable',
                'blockQuote',
                'pageBreak',
                'horizontalLine',
                'specialCharacters',
                '|',
            ],
            shouldNotGroupWhenFull: true,
        },
        image: {
            resizeUnit: 'px' as const,
            resizeOptions: [
                {
                    name: 'resizeImage:original',
                    label: 'Original',
                    value: null,
                    icon: 'original',
                },
                {
                    name: 'resizeImage:100',
                    label: '100px',
                    value: '100',
                    icon: 'small',
                },
                {
                    name: 'resizeImage:200',
                    label: '200px',
                    value: '200',
                    icon: 'large',
                },
            ],
            toolbar: [
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side',
                '|',
                'resizeImage:original',
                'resizeImage:100',
                'resizeImage:200',
            ],
        },
        language: {
            ui: 'es', // Interfaz de usuario en español
            content: 'es', // Contenido editable en español (opcional)
        },
        translations: [esTranslations],
    } as any,
    editor: ClassicEditor,
};
