import { Translation } from 'primeng/api';

/**
 * Traducción de PrimeNG al español, como objeto estático.
 *
 * Sustituye a la carga asíncrona que hacía ngx-translate desde
 * `assets/i18n/es.json`: el sistema es monolingüe y una dependencia asíncrona
 * en el arranque es justamente lo que hay que evitar
 * (docs/architecture/mi-pimpollito-plan.md §4.5).
 */
export const PRIMENG_ES: Translation = {
    startsWith: 'Empieza por',
    contains: 'Contiene',
    notContains: 'No contiene',
    endsWith: 'Termina en',
    equals: 'Igual a',
    notEquals: 'Distinto de',
    noFilter: 'Sin filtro',
    lt: 'Menor que',
    lte: 'Menor o igual que',
    gt: 'Mayor que',
    gte: 'Mayor o igual que',
    is: 'Es',
    isNot: 'No es',
    before: 'Antes de',
    after: 'Después de',
    dateIs: 'Fecha igual a',
    dateIsNot: 'Fecha distinta de',
    dateBefore: 'Fecha antes de',
    dateAfter: 'Fecha después de',
    clear: 'Limpiar',
    apply: 'Aplicar',
    matchAll: 'Coincidir todos',
    matchAny: 'Coincidir alguno',
    addRule: 'Añadir regla',
    removeRule: 'Quitar regla',
    accept: 'Sí',
    reject: 'No',
    choose: 'Elegir',
    upload: 'Subir',
    cancel: 'Cancelar',
    pending: 'Pendiente',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    dayNames: [
        'domingo',
        'lunes',
        'martes',
        'miércoles',
        'jueves',
        'viernes',
        'sábado',
    ],
    dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'],
    dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'],
    monthNames: [
        'enero',
        'febrero',
        'marzo',
        'abril',
        'mayo',
        'junio',
        'julio',
        'agosto',
        'septiembre',
        'octubre',
        'noviembre',
        'diciembre',
    ],
    monthNamesShort: [
        'ene',
        'feb',
        'mar',
        'abr',
        'may',
        'jun',
        'jul',
        'ago',
        'sep',
        'oct',
        'nov',
        'dic',
    ],
    chooseYear: 'Elegir año',
    chooseMonth: 'Elegir mes',
    chooseDate: 'Elegir fecha',
    prevDecade: 'Década anterior',
    nextDecade: 'Década siguiente',
    prevYear: 'Año anterior',
    nextYear: 'Año siguiente',
    prevMonth: 'Mes anterior',
    nextMonth: 'Mes siguiente',
    prevHour: 'Hora anterior',
    nextHour: 'Hora siguiente',
    prevMinute: 'Minuto anterior',
    nextMinute: 'Minuto siguiente',
    prevSecond: 'Segundo anterior',
    nextSecond: 'Segundo siguiente',
    am: 'a. m.',
    pm: 'p. m.',
    today: 'Hoy',
    weekHeader: 'Sem',
    firstDayOfWeek: 1,
    dateFormat: 'dd/mm/yy',
    weak: 'Débil',
    medium: 'Media',
    strong: 'Fuerte',
    passwordPrompt: 'Escribe una contraseña',
    emptyMessage: 'No se han encontrado resultados',
    emptyFilterMessage: 'No se han encontrado resultados',
};
